### ISSUE TITLE
Consider using mountable engine for routes

### ISSUE THREAD

**Issue by macowie** [infinum/phrasing#38]
Hi! I'm poking around with this gem (very nice!), but one pain point I ran into was how it injects the routes directly into the application instead of using a mountable engine. I use a catch-all GET route at the bottom of my apps routes to handle any request gracefully, but Phrasing's routes get tacked on afterward, making them inaccessible by default. 

My workaround in case anyone else has this issue was to add a constraint on my route to ignore phrasing

```ruby
get '*path' => 'pages#show', :as => :page, constraints: lambda { |request| !(request.path =~ /phrasing/) }
```

**Comment by DamirSvrtan** [comment]
Hey @macowie,

Thnx for reporting this, however I'm not sure if Phrasing would totally count as a isolated Rails Engine since you must access some routes from your application (e.g. the update route you're hitting everytime you edit a phrase). 

That route still has to be outside of the Rails engine and your problem would still persist. Am I right?

**Comment by DamirSvrtan** [comment]
I'm closing this. If you think i'm wrong, please update me.
