### ISSUE TITLE
Is there a correct way to edit the help docs?

### ISSUE THREAD

**Issue by CryptoSnippets** [infinum/phrasing#45]
Hi, I've tried editing **help.html.haml** to simplify instructions for my users, but the changes only appear in development and don't deploy to staging or production.  Is there a correct way to customize the help page?

**Comment by DamirSvrtan** [comment]
Can you give a bit more detail on how you tried to edit the help.html.haml file?

**Comment by CryptoSnippets** [comment]
I edited it in the gem's install directory.
>> /home/user/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/phrasing-4.0.0rc9/app/views/phrasing_phrases/htlp.html.haml

**Comment by DamirSvrtan** [comment]
Then it wont be changed since you're not deploying that piece of code to your staging/production environment - it stays on your development machine.

Create a view inside your app on this path: app/views/phrasing_phrases/help.html.haml and write the appropriate content in there.

Because Rails looks for views inside your app before looking for it in other Rails engines, your help html file will be picked up before Phrasing's will.

**Comment by CryptoSnippets** [comment]
Thank you, Damir!
